version: "3.9"

services:
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: note_script-app
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - "5002:${PORT}"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: note_script-redis
    ports:
      - "6379:6379"
    restart: always